import { EMPTY } from '~constants'
import { formatSpeedLimits, getMaxCR } from '~utils/creatures'

describe('formatSpeedLimits', () => {
  it('should format speed limitations', () => {
    expect(formatSpeedLimits(1)).toEqual(EMPTY)
    expect(formatSpeedLimits(2)).toMatch(/((fly){1}.+(swim){1})/)
    expect(formatSpeedLimits(3)).toMatch(/((fly){1}.+(swim){1})/)
    expect(formatSpeedLimits(4)).toMatch(/((fly){1}.+(swim){0})/)
    expect(formatSpeedLimits(5)).toMatch(/((fly){1}.+(swim){0})/)
    expect(formatSpeedLimits(6)).toMatch(/((fly){1}.+(swim){0})/)
    expect(formatSpeedLimits(7)).toMatch(/((fly){1}.+(swim){0})/)
    expect(formatSpeedLimits(8)).toEqual(EMPTY)
    expect(formatSpeedLimits(9)).toEqual(EMPTY)
    expect(formatSpeedLimits(10)).toEqual(EMPTY)
    expect(formatSpeedLimits(11)).toEqual(EMPTY)
    expect(formatSpeedLimits(12)).toEqual(EMPTY)
    expect(formatSpeedLimits(13)).toEqual(EMPTY)
    expect(formatSpeedLimits(14)).toEqual(EMPTY)
    expect(formatSpeedLimits(15)).toEqual(EMPTY)
    expect(formatSpeedLimits(16)).toEqual(EMPTY)
    expect(formatSpeedLimits(17)).toEqual(EMPTY)
    expect(formatSpeedLimits(18)).toEqual(EMPTY)
    expect(formatSpeedLimits(19)).toEqual(EMPTY)
    expect(formatSpeedLimits(20)).toEqual(EMPTY)
  })
})

describe('getMaxCR', () => {
  it('should calcutate max CR', () => {
    expect(getMaxCR({ level: 1 })).toEqual(null)
    expect(getMaxCR({ level: 2 })).toEqual(0.25)
    expect(getMaxCR({ level: 3 })).toEqual(0.25)
    expect(getMaxCR({ level: 4 })).toEqual(0.5)
    expect(getMaxCR({ level: 5 })).toEqual(0.5)
    expect(getMaxCR({ level: 6 })).toEqual(0.5)
    expect(getMaxCR({ level: 7 })).toEqual(0.5)
    expect(getMaxCR({ level: 8 })).toEqual(1)
    expect(getMaxCR({ level: 9 })).toEqual(1)
    expect(getMaxCR({ level: 10 })).toEqual(1)
    expect(getMaxCR({ level: 11 })).toEqual(1)
    expect(getMaxCR({ level: 12 })).toEqual(1)
    expect(getMaxCR({ level: 13 })).toEqual(1)
    expect(getMaxCR({ level: 14 })).toEqual(1)
    expect(getMaxCR({ level: 15 })).toEqual(1)
    expect(getMaxCR({ level: 16 })).toEqual(1)
    expect(getMaxCR({ level: 17 })).toEqual(1)
    expect(getMaxCR({ level: 18 })).toEqual(1)
    expect(getMaxCR({ level: 19 })).toEqual(1)
    expect(getMaxCR({ level: 20 })).toEqual(1)
  })

  it('should calcutate max CR for Circle of the Moon', () => {
    const circleForms = true

    expect(getMaxCR({ level: 1, circleForms })).toEqual(null)
    expect(getMaxCR({ level: 2, circleForms })).toEqual(1)
    expect(getMaxCR({ level: 3, circleForms })).toEqual(1)
    expect(getMaxCR({ level: 4, circleForms })).toEqual(1)
    expect(getMaxCR({ level: 5, circleForms })).toEqual(1)
    expect(getMaxCR({ level: 6, circleForms })).toEqual(2)
    expect(getMaxCR({ level: 7, circleForms })).toEqual(2)
    expect(getMaxCR({ level: 8, circleForms })).toEqual(2)
    expect(getMaxCR({ level: 9, circleForms })).toEqual(3)
    expect(getMaxCR({ level: 10, circleForms })).toEqual(3)
    expect(getMaxCR({ level: 11, circleForms })).toEqual(3)
    expect(getMaxCR({ level: 12, circleForms })).toEqual(4)
    expect(getMaxCR({ level: 13, circleForms })).toEqual(4)
    expect(getMaxCR({ level: 14, circleForms })).toEqual(4)
    expect(getMaxCR({ level: 15, circleForms })).toEqual(5)
    expect(getMaxCR({ level: 16, circleForms })).toEqual(5)
    expect(getMaxCR({ level: 17, circleForms })).toEqual(5)
    expect(getMaxCR({ level: 18, circleForms })).toEqual(6)
    expect(getMaxCR({ level: 19, circleForms })).toEqual(6)
    expect(getMaxCR({ level: 20, circleForms })).toEqual(6)
  })
})
