name: Sync with 5etools
on:
  pull_request:
jobs:
  sync-with-5etools:
    if: startsWith(github.head_ref, 'renovate/5etools-')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node and restore dependencies
        uses: ./.github/actions/setup
      - name: Sync with 5etools
        run: yarn sync-with-5etools
      - name: Commit changes
        uses: github-actions-x/commit@v2.9
        with:
          commit-message: 'feat: sync with 5etools'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: ${{ github.head_ref }}
          rebase: true
